INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (1, 'Aplikovaná elektrotechnika');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (2, 'Copywriting');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (3, 'Daně');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (4, 'Ekonomie');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (5, 'Elektronika a informační technologie');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (6, 'Event management, produkce');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (7, 'Finanční plánování');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (8, 'Fotografování, nahrávání videa a zvuku');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (9, 'Fyzika');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (10, 'Geografie');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (11, 'Grafický design');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (12, 'Informační management');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (13, 'Informační systémy');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (14, 'Konstruování strojů a technických zařízení');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (15, 'Kybernetika');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (16, 'Marketing');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (17, 'Matematika');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (18, 'Materiály a technologie pro elektrotechniku');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (19, 'Počítačové modelování');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (20, 'Podniková ekonomika');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (21, 'Produktový design');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (22, 'Produktový management');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (23, 'Projektový management');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (24, 'Průmyslové inženýrství');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (25, 'Softwarové inženýrství');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (26, 'Správa sociálních sítí');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (27, 'Statistika a datová analýza');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (28, 'Stavba energetických strojů a zařízení');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (29, 'Stavební a městské inženýrství');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (30, 'Strojírenské technologie a materiály');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (31, 'Strojní inženýrství');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (32, 'Systémové inženýrství a informatika');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (33, 'Teorie a stavba strojů');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (34, 'Účetnictví');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (35, 'Územní plánování');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (36, 'Výkonové systémy a elektroenergetika');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (37, 'Výpočetní technika');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (38, 'Výtvarná umění');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (39, 'Vývoj desktopových aplikací');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (40, 'Vývoj mobilních aplikací');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (41, 'Vývoj webových aplikací');
INSERT INTO `studenti-spolu`.field (id_field, name) VALUES (42, '(Jiné)');